### ISSUE TITLE
Utiliser la licence MIT (ou LO) ? 

### ISSUE THREAD

**Issue by bzg** [eig-2017/pointk#6]
`pointk` est cité comme logiciel libre dans le brouillon de rapport sur la première promotion EIG.

`\o/`

Par contre, la licence actuelle ne figure pas dans les [licences homologuées](https://www.data.gouv.fr/fr/licences).

Je propose de passer en MIT (ou LO) - une préférence particulière ?

**Comment by Tristramg** [comment]
Roohh… nul.

Plutôt MIT vu que c’est du code.

**Comment by fchabouis** [comment]
Une petite mise en valeur de l'outil serait bénéfique...on n'a même pas mis la demo ?
On se prend un aprem pour faire ça un de ces 4 Tristram ?

**Comment by bzg** [comment]
Merci pour les réponses, j'ai donc mis la MIT.

Du coup je me sens hyper rabat-joie.
